# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

changelog:
  exclude:
    scopes: ["deps"]
  categories:
    - title: "💥 Breaking Changes"
      increment: ["feat!"]
    - title: "✨ New Features"
      increment: ["feat"]
    - title: "🐛 Bug Fixes"
      increment: ["fix"]
      exclude:
        scopes: ["internal"]
    - title: "📚 Documentation"
      types: ["docs"]
      scopes: ["api"]
  
