name: Release and Deploy GitHub Action

concurrency: deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-me:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.created }}
      release: ${{ steps.release.outputs.release }}

    steps:
      - uses: actions/checkout@v3

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: output-as-artifact
      #     path: output.txt

      - name: Run ReleaseMe
        id: release
        uses: ./
        with:
          token: ${{ github.token }}
          prefix: v
          # artifacts: output-as-artifact

  release-action:
    name: Release GitHub Action
    runs-on: ubuntu-latest
    needs: release-me
    if: needs.release-me.outputs.created

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ fromJSON(needs.release-me.outputs.release).tag_name }}

      - name: Update the ${{ fromJSON(needs.release-me.outputs.release).tag_name }} tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ fromJSON(needs.release-me.outputs.release).tag_name }}